# Generated by Django 2.2.1 on 2019-11-01 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('stars', models.IntegerField()),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_app.Package')),
            ],
        ),
    ]
